### ISSUE TITLE
 Check failed: outstanding_proxy_fetches_.empty()

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#875]
I noticed this CHECK failure while debugging something else:
```
Check failed: outstanding_proxy_fetches_.empty().
```
Searching shows that previously it was mentioned here as well: https://github.com/pagespeed/ngx_pagespeed/issues/330#issuecomment-17430161

I suspect this reproduces with shutdowns under high loads, which is something that we might want to test to see if something needs fixing.

**Comment by oschaaf** [comment]
Another different CHECK failure (with trunk-tracking),  while trying to reproduce.
Reproduces easily on my machine by shutting down nginx while `ab` is benchmarking.

```
(gdb) bt
#0  base::debug::(anonymous namespace)::DebugBreak () at third_party/chromium/src/base/debug/debugger_posix.cc:246
#1  0x0000000000496e98 in base::debug::BreakDebugger () at third_party/chromium/src/base/debug/debugger_posix.cc:259
#2  0x000000000047def5 in (anonymous namespace)::LogMessageHandler (severity=4, file=<optimized out>, line=<optimized out>, message_start=<optimized out>, str=...) at /home/oschaaf/Code/google/ngxps-ttpr/ngx_pagespeed/src/log_message_handler.cc:66
#3  0x0000000000497e9a in logging::LogMessage::~LogMessage (this=0x7fffffffd9b0, __in_chrg=<optimized out>) at third_party/chromium/src/base/logging.cc:572
#4  0x00000000004fa1cd in net_instaweb::CategorizedRefcount<net_instaweb::RewriteDriver, net_instaweb::RewriteDriver::RefCategory>::ReleaseRefMutexHeld (this=0x26b0f50, category=net_instaweb::RewriteDriver::kRefUser) at ./pagespeed/kernel/util/categorized_refcount.h:118
#5  0x00000000004f3e61 in net_instaweb::RewriteDriver::DropReference (this=0x26b0cc0, ref_cat=net_instaweb::RewriteDriver::kRefUser) at net/instaweb/rewriter/rewrite_driver.cc:3232
#6  0x00000000004f061d in net_instaweb::RewriteDriver::Cleanup (this=0x26b0cc0) at net/instaweb/rewriter/rewrite_driver.cc:2580
#7  0x000000000057cc65 in net_instaweb::ServerContext::ShutDownDrivers (this=0x15af3a0) at net/instaweb/rewriter/server_context.cc:873
#8  0x000000000050a8fe in net_instaweb::RewriteDriverFactory::ShutDown (this=0x13dbf50) at net/instaweb/rewriter/rewrite_driver_factory.cc:722
#9  0x00000000006001e3 in net_instaweb::SystemRewriteDriverFactory::ShutDown (this=0x13dbf50) at pagespeed/system/system_rewrite_driver_factory.cc:483
#10 0x000000000048bb23 in net_instaweb::NgxRewriteDriverFactory::~NgxRewriteDriverFactory (this=0x13dbf50, __in_chrg=<optimized out>) at /home/oschaaf/Code/google/ngxps-ttpr/ngx_pagespeed/src/ngx_rewrite_driver_factory.cc:99
#11 0x000000000048bc8b in net_instaweb::NgxRewriteDriverFactory::~NgxRewriteDriverFactory (this=0x13dbf50, __in_chrg=<optimized out>) at /home/oschaaf/Code/google/ngxps-ttpr/ngx_pagespeed/src/ngx_rewrite_driver_factory.cc:102
#12 0x00000000004833d8 in net_instaweb::(anonymous namespace)::ps_cleanup_srv_conf (data=0x15a79e0) at /home/oschaaf/Code/google/ngxps-ttpr/ngx_pagespeed/src/ngx_pagespeed.cc:732
#13 0x000000000040e852 in ngx_destroy_pool (pool=0x13b7b00) at src/core/ngx_palloc.c:48
#14 0x000000000042c5e0 in ngx_master_process_exit (cycle=cycle@entry=0x13cd610) at src/os/unix/ngx_process_cycle.c:730
#15 0x000000000042e5bc in ngx_single_process_cycle (cycle=cycle@entry=0x13cd610) at src/os/unix/ngx_process_cycle.c:329
#16 0x000000000040d498 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:404
```

**Comment by oschaaf** [comment]
Should be fixed on trunk-tracking with the single fd-change and the subsequent changes for explicitly controlling the way we shut down.
